# Reek configuration. See https://github.com/troessner/reek

exclude_paths:
  - .bundle
  - .git-hooks
  - db/migrate
  - test

detectors:
  UtilityFunction:
    public_methods_only: true

  IrresponsibleModule:
    exclude:
      - Earl::QuestionHandler::QuestionState    # Simple state struct
      - Earl::SessionStore::PersistedSession    # Simple data struct
      - Earl::Mcp::Config::ApiConfig            # Simple config struct

  UncommunicativeVariableName:
    exclude:
      - Earl::QuestionHandler   # Short block vars (i, q) in compact iteration
      - Earl::SessionStore      # Short block var (v) in transform_values

  TooManyInstanceVariables:
    exclude:
      - Earl::Runner            # Main coordinator: config, store, manager, mattermost, executor, handler, state, thread
      - Earl::Mattermost        # WebSocket client: config, api, callbacks (x2), channel_ids, ws
      - Earl::ClaudeSession     # Process state, callbacks, options, session_id, mutex, stats
      - Earl::CommandExecutor   # Manager, mattermost, config, working_dirs, permission_modes
      - Earl::Mcp::Config       # Env-based config with many fields

  TooManyMethods:
    exclude:
      - Earl::Runner            # Coordinator wires many concerns: signals, messages, commands, reactions, idle
      - Earl::ClaudeSession     # Process lifecycle + CLI args + event processing (split across 3 modules)
      - Earl::Mattermost        # WebSocket handling + REST API + event dispatch (split across module)
      - Earl::CommandExecutor   # One method per command + formatting helpers

  DataClump:
    exclude:
      - Earl::Runner            # thread_id, text, channel_id travel together through message routing
      - Earl::SessionManager    # channel_id, working_dir travel together for session creation
      - Earl::CommandExecutor   # thread_id, channel_id travel together through command routing
      - Earl::Mcp::ApprovalHandler # tool_name, input travel together through approval flow

  TooManyStatements:
    max_statements: 8
    exclude:
      - Earl::ClaudeSession::Stats#format_summary       # Builds multi-field summary string
      - Earl::Runner#initialize                          # Main coordinator initializes many collaborators
      - Earl::CommandExecutor#execute                    # Case statement dispatches to 8 commands
      - Earl::Mcp::ApprovalHandler#poll_for_reaction     # WebSocket polling loop with reaction matching
      - Earl::QuestionHandler#handle_reaction            # Multi-step reaction → answer flow
      - Earl::QuestionHandler#post_current_question      # Builds and posts formatted question
      - Earl::SessionStore#write_store                   # Atomic file write with temp file

  FeatureEnvy:
    exclude:
      - Earl::ClaudeSession::EventProcessing#emit_text_content    # Iterates content blocks
      - Earl::ClaudeSession::EventProcessing#emit_tool_use_blocks # Iterates content blocks
      - Earl::ClaudeSession::EventProcessing#extract_model_usage  # Reads model usage hash fields
      - Earl::ClaudeSession::EventProcessing#extract_usage        # Reads usage hash fields
      - Earl::ClaudeSession::EventProcessing#format_result_log    # Builds formatted log string
      - Earl::Config#parse_channels                               # Parses env var string
      - Earl::CommandExecutor#format_stats                        # Reads stats struct fields
      - Earl::CommandExecutor#append_optional_stats               # Reads stats struct fields
      - Earl::Runner#log_session_stats                            # Reads session stats
      - Earl::QuestionHandler#handle_tool_use                     # Reads tool_use hash fields

  ControlParameter:
    exclude:
      - Earl::Runner#process_message                     # channel_id fallback is idiomatic
      - Earl::SessionManager#build_permission_config     # channel_id fallback is idiomatic
      - Earl::Mcp::ApprovalHandler#format_input          # tool_name dispatches formatting
      - Earl::Mcp::ApprovalHandler#poll_for_reaction     # post_id filters reactions
      - Earl::Mcp::Server#tools_call_response            # params dispatches tool call

  DuplicateMethodCall:
    exclude:
      - Earl::Mcp::ApprovalHandler#poll_for_reaction     # msg.data checks in WebSocket callback
      - Earl::Mcp::ApprovalHandler#allowed_reactor?      # config.allowed_users check + use
      - Earl::Mcp::Server#tools_call_response            # error.message in rescue
      - Earl::QuestionHandler#handle_reaction             # state field access in multi-step flow
      - Earl::QuestionHandler#build_answer_json           # question field access in iteration

  LongParameterList:
    exclude:
      - Earl::SessionManager # create_session and build_persisted pass through session config
