# Reek configuration. See https://github.com/troessner/reek

exclude_paths:
  - .bundle
  - .git-hooks
  - db/migrate
  - test

detectors:
  UtilityFunction:
    public_methods_only: true


  TooManyStatements:
    max_statements: 10
    exclude:
      - Earl::ClaudeSession#send_message                                    # Process lifecycle with stdin write + event setup (12)
      - Earl::ClaudeSession::Stats#format_summary                           # Builds multi-field summary string (11)
      - Earl::CronParser#parse_part                                         # Multi-branch regex parsing (14)
      - Earl::HeartbeatScheduler::ConfigReloading#reload_definitions        # Diff + add/remove/update heartbeats (18)
      - Earl::HeartbeatScheduler::Execution#disable_heartbeat               # YAML read + modify + write (13)
      - Earl::HeartbeatScheduler::Execution#execute_heartbeat               # Build post + session + run + finalize (14)
      - Earl::HeartbeatScheduler::Execution#run_session                     # Session lifecycle with callbacks (11)
      - Earl::Mattermost::ApiClient#send_request                            # Retry loop with connection setup (12)
      - Earl::Mattermost#get_thread_posts                                   # Fetch + parse + sort thread posts (13)
      - Earl::Mcp::ApprovalHandler::ReactionPolling#poll_for_reaction       # WebSocket polling loop with reaction matching (17)
      - Earl::Mcp::HeartbeatHandler::EntryBuilder#build_entry               # Build struct from arguments hash (13)
      - Earl::Mcp::Server#tools_call_response                               # Extract params, call handler, format response (13)
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#create_spawned_session     # Extract params + create tmux target + persist + format (12)
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#poll_confirmation         # WebSocket polling loop with reaction matching (18)
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#post_confirmation_request # Build message + post + parse response (12)
      - Earl::QuestionHandler#handle_reaction                               # Multi-step reaction → answer flow (13)
      - Earl::SessionManager#resume_or_create                               # Resume with fallback to create (11)
      - Earl::Tmux#list_all_panes                                           # Aggregate panes across sessions (12)
      - Earl::TmuxSessionStore#read_store                                   # JSON parse + validate + deserialize (13)
      - Earl::TmuxSessionStore#write_store                                  # Atomic JSON file write (11)

  FeatureEnvy:
    exclude:
      - Earl::ClaudeSession::EventProcessing#emit_tool_use_blocks # Iterates content blocks
      - Earl::ClaudeSession::EventProcessing#extract_usage        # Reads usage hash fields
      - Earl::ClaudeSession::EventProcessing#extract_model_usage  # Reads model usage hash fields
      - Earl::ClaudeSession::EventProcessing#format_result_log    # Builds formatted log string
      - Earl::CommandExecutor#execute                              # Reads command struct fields
      - Earl::CommandExecutor::StatsFormatter#append_optional_stats  # Reads stats struct fields
      - Earl::CommandExecutor::SessionHandler#format_claude_pane_row # Formats pane hash fields
      - Earl::CommandExecutor::HeartbeatDisplay#format_heartbeat_row # Formats heartbeat status
      - Earl::CommandExecutor::HeartbeatDisplay#format_heartbeats    # Builds lines array
      - Earl::CommandExecutor::SessionHandler#handle_session_input   # Reads CommandContext fields for tmux forwarding
      - Earl::CommandExecutor#reply                                  # Reads CommandContext fields for Mattermost post
      - Earl::Config#parse_channels                                # Parses env var string
      - Earl::CronParser#matches?                                  # Checks time fields against cron fields
      - Earl::CronParser#parse_expression                          # Parses expression parts array
      - Earl::HeartbeatConfig#build_definition                     # Reads config hash to build struct
      - Earl::HeartbeatScheduler#dispatch_heartbeat                   # Sets state fields for heartbeat dispatch
      - Earl::HeartbeatScheduler::Execution#permission_config       # Reads config fields to build env hash
      - Earl::HeartbeatScheduler::Execution#create_header_post       # Reads heartbeat definition fields
      - Earl::HeartbeatScheduler::Execution#create_heartbeat_session # Reads heartbeat definition fields
      - Earl::HeartbeatScheduler::Execution#run_session             # Reads session/definition fields
      - Earl::HeartbeatScheduler::Execution#wait_for_completion     # Reads session state
      - Earl::HeartbeatScheduler::Execution#finalize_heartbeat      # Reads heartbeat definition fields
      - Earl::HeartbeatScheduler::ConfigReloading#update_existing_definitions # Updates state objects from new definitions
      - Earl::HeartbeatScheduler::StatusFormatting#build_status    # Builds status from definition fields
      - Earl::Mattermost#parse_post_response                           # Reads response hash fields
      - Earl::Mattermost::ApiClient#build_request                      # Builds HTTP request from params
      - Earl::Mattermost::WebSocketHandling#websocket_handler_map      # Reads event data fields
      - Earl::Mcp::ApprovalHandler#call                            # Reads arguments hash to delegate
      - Earl::Mcp::HeartbeatHandler::EntryBuilder#build_entry                    # Reads arguments hash to build struct
      - Earl::Mcp::HeartbeatHandler#format_heartbeat               # Reads heartbeat entry fields
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#create_spawned_session              # Reads SpawnRequest fields for session creation
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#post_confirmation_request           # Reads SpawnRequest fields for confirmation message
      - Earl::Mcp::TmuxHandler::PaneOperations#format_pane                         # Reads pane hash fields for formatting
      - Earl::Mcp::TmuxHandler::PaneOperations#detect_pane_status                  # Reads capture output to classify status
      - Earl::Memory::PromptBuilder#build                          # Assembles sections array into string
      - Earl::Memory::Store#collect_entries                         # Builds entries array from file lines
      - Earl::Memory::Store#grep_files                              # Builds results array from file matches
      - Earl::QuestionHandler#handle_tool_use                       # Reads tool_use hash fields
      - Earl::QuestionHandler#post_current_question                 # Reads question state fields
      - Earl::Runner::MessageHandling#enqueue_message               # Reads UserMessage fields for queue operations
      - Earl::Runner::MessageHandling#handle_incoming_message       # Reads UserMessage fields for routing
      - Earl::Runner::MessageHandling#process_message               # Reads UserMessage fields for session processing
      - Earl::Runner::ResponseLifecycle#setup_callbacks             # Wires session callbacks to response handlers
      - Earl::StreamingResponse#format_tool_use                     # Reads tool_use hash fields
      - Earl::TmuxMonitor::PollState#update_stall_count             # Reads entry hash fields

  ControlParameter:
    exclude:
      - Earl::Mcp::HeartbeatHandler#call                   # name dispatches to CRUD handler
      - Earl::SessionManager#build_permission_config       # channel_id fallback is idiomatic
      - Earl::Mcp::ApprovalHandler#format_input            # tool_name dispatches formatting
      - Earl::Mcp::ApprovalHandler::ReactionPolling#poll_for_reaction       # post_id filters reactions
      - Earl::Mcp::Server#tools_call_response              # params dispatches tool call
      - Earl::Mcp::MemoryHandler#call                      # name dispatches to save/search handlers
      - Earl::ToolInputFormatter#extract_tool_detail_from   # input nil-guard is defensive
      - Earl::TmuxMonitor#alert_for_state                   # state dispatches alert type
      - Earl::TmuxMonitor::PollState#no_pending_for?        # name filters pending interactions
      - Earl::Mcp::TmuxHandler#call                        # name dispatches to action handler
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#poll_confirmation             # post_id filters reactions

  RepeatedConditional:
    exclude:
      - Earl::Mcp::HeartbeatHandler                      # heartbeats[name] existence check across CRUD methods

  DuplicateMethodCall:
    exclude:
      - Earl::ClaudeSession::ProcessManagement#join_threads                  # @runtime.process_state in different thread join calls
      - Earl::CronParser#parse_expression                                    # parts.size checked then parts accessed
      - Earl::CronParser#parse_part                                          # Regexp.last_match across case branches
      - Earl::HeartbeatConfig#load_definitions                               # data["heartbeats"] guard then access
      - Earl::HeartbeatScheduler::Execution#wait_for_completion              # Time.now in polling loop (must be fresh each iteration)
      - Earl::Mcp::HeartbeatHandler::EntryBuilder#merge_entry                # entry["schedule"] across case branches
      - Earl::Mcp::TmuxHandler::PaneOperations#kill_tmux_session             # @tmux_store.delete in happy path + NotFound rescue
      - Earl::QuestionHandler#handle_reaction                                # @mutex.synchronize in different scopes
      - Earl::StreamingResponse::Finalization#finalize                       # @post_state.reply_post_id in different branch paths
      - Earl::Tmux#list_all_panes                                            # fields.size + error.message in rescue
      - Earl::Tmux#list_sessions                                             # error.message in rescue branches
      - Earl::Tmux#wait_for_text                                             # Time.now in polling loop (must be fresh each iteration)
      - Earl::TmuxSessionStore#cleanup!                                      # @mutex.synchronize in different branches
      - Earl::TmuxSessionStore#read_store                                    # error.message in rescue


  DataClump:
    exclude:
      - Earl::Runner                                       # channel_id + thread_id travel through response lifecycle methods
      - Earl::SessionManager                               # session_config + thread_id travel through create/resume methods
      - Earl::CommandExecutor::SpawnHandler                 # ctx + req travel through spawn flow methods
      - Earl::CommandExecutor::StatsFormatter               # lines + stats travel through stat formatting methods

  LongParameterList:
    exclude:
      - Earl::CommandExecutor#initialize                  # 6 keyword params for dependency injection
      - Earl::CommandExecutor::UsageHandler#append_category_line     # Formatting params for context display
      - Earl::CommandExecutor::SpawnHandler#spawn_tmux_session      # ctx + 3 keyword params for session creation
      - Earl::SessionManager#resume_or_create              # thread_id + short_id + persisted + session_config
      - Earl::SessionManager#build_persisted               # session + keyword params for persistence
      - Earl::Mcp::ApprovalHandler::ReactionPolling#poll_for_reaction       # WebSocket + post_id + request + deadline for polling
      - Earl::Tmux#wait_for_text                            # Polling config: session, text, timeout, interval, lines
      - Earl::Tmux#create_window                             # Tmux window creation params: session, name, command, working_dir
      - Earl::TmuxMonitor#alert_for_state                   # State transition context params
