# Reek configuration. See https://github.com/troessner/reek

exclude_paths:
  - .bundle
  - .git-hooks
  - db/migrate
  - test

detectors:
  UtilityFunction:
    public_methods_only: true

  # Disabled: all 42 exclusions were structural — methods whose purpose is to
  # read from external data (hashes, structs, Data objects) inherently trigger
  # this detector. No actionable signal for this codebase.
  FeatureEnvy:
    enabled: false

  # Disabled: all 14 exclusions were structural — Time.now in polling loops,
  # error.message in rescue branches, guard-then-access patterns. These are
  # intentional repeated calls, not candidates for local variable extraction.
  DuplicateMethodCall:
    enabled: false

  TooManyStatements:
    max_statements: 14
    exclude:
      - Earl::HeartbeatScheduler::ConfigReloading#reload_definitions    # Diff + add/remove/update heartbeats (18)
      - Earl::HeartbeatScheduler::Execution#execute_heartbeat           # Build post + session + run + finalize (16)
      - Earl::Mcp::ApprovalHandler::ReactionPolling#poll_for_reaction   # WebSocket polling loop with reaction matching (17)
      - Earl::Mcp::HeartbeatHandler::EntryBuilder#build_entry           # Build struct from arguments hash (20)
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#poll_confirmation     # WebSocket polling loop with reaction matching (18)
      - Earl::QuestionHandler#handle_reaction                           # Multi-step reaction → answer flow (15)

  ControlParameter:
    exclude:
      - Earl::SessionManager#build_permission_config                   # channel_id fallback is idiomatic
      - Earl::Mcp::ApprovalHandler::ReactionPolling#poll_for_reaction  # post_id filters reactions
      - Earl::Mcp::Server#tools_call_response                         # params dispatches tool call
      - Earl::ToolInputFormatter#extract_tool_detail_from              # input nil-guard is defensive
      - Earl::TmuxMonitor#alert_for_state                             # state dispatches alert type
      - Earl::TmuxMonitor::PollState#no_pending_for?                  # name filters pending interactions
      - Earl::Mcp::TmuxHandler::SpawnConfirmation#poll_confirmation   # post_id filters reactions

  RepeatedConditional:
    exclude:
      - Earl::Mcp::HeartbeatHandler  # heartbeats[name] existence check across CRUD methods

  DataClump:
    exclude:
      - Earl::Runner                            # channel_id + thread_id travel through response lifecycle methods
      - Earl::SessionManager                    # session_config + thread_id travel through create/resume methods
      - Earl::CommandExecutor::SpawnHandler      # ctx + req travel through spawn flow methods
      - Earl::CommandExecutor::StatsFormatter    # lines + stats travel through stat formatting methods

  LongParameterList:
    max_params: 5
    overrides:
      initialize:
        max_params: 7
    exclude:
      - Earl::CommandExecutor#initialize  # 6 keyword params for dependency injection
