# Reek configuration. See https://github.com/troessner/reek

exclude_paths:
  - .bundle
  - .git-hooks
  - db/migrate
  - test

detectors:
  UtilityFunction:
    public_methods_only: true
  TooManyStatements:
    max_statements: 10
  TooManyMethods:
    max_methods: 20
